apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "az-sb-consumer-go-poc.fullname" . }}-configmap
data:
{{- range $key,$value := .Values.envVariables }}
{{ $key | quote | indent 2 }}: {{ $value | quote }} 
{{- end }}
